import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, ChevronRight, MapPin, Pencil, Trash2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Navbar } from "../../../components/layout/Navbar";
import { PageContainer } from "../../../components/layout/PageContainer";
import { Button, Card, EmptyState, Input, Modal, Textarea } from "../../../components/ui";
import { ProductGrid } from "../../../components/product/ProductGrid";
import { useCart } from "../../../hooks/useCart";
import { placeOrder } from "../../../services/orders.api";
import * as addressesApi from "../../../services/addresses.api";
import { listProducts } from "../../../services/products.api";
import { Address, ShippingInfo } from "../../../types";
import { formatCurrency } from "../../../utils/formatCurrency";
import { useToastStore } from "../../../store/toastStore";

const blank = (): addressesApi.AddressInput => ({ label: "Home", fullName: "", countryCode: "+91", phone: "", addressLine: "", city: "", state: "", postalCode: "", notes: "" });

export default function CheckoutPage() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const push = useToastStore((s) => s.push);
  const { items, cartQuery, updateItem, removeItem } = useCart();
  const [draftQuantities, setDraftQuantities] = useState<Record<string, number>>({});
  const orderActionRef = useRef<HTMLDivElement>(null);
  const [orderActionVisible, setOrderActionVisible] = useState(true);
  const addresses = useQuery({ queryKey: ["addresses"], queryFn: addressesApi.listAddresses });
  const [selectedId, setSelectedId] = useState<string | null>(null); const [pickerOpen, setPickerOpen] = useState(false); const [editOpen, setEditOpen] = useState(false); const [confirmed, setConfirmed] = useState<string | null>(null);
  useEffect(() => { if (!selectedId && addresses.data?.[0]) setSelectedId(addresses.data[0].id); }, [addresses.data, selectedId]);
  useEffect(() => {
    const target = orderActionRef.current;
    if (!target) return;
    const observer = new IntersectionObserver(
      ([entry]) => setOrderActionVisible(entry.isIntersecting),
      { rootMargin: "0px 0px -136px 0px", threshold: 0 }
    );
    observer.observe(target);
    return () => observer.disconnect();
  }, [selectedId, items.length]);
  const selected = addresses.data?.find((address) => address.id === selectedId) ?? null;
  const related = useQuery({ queryKey: ["checkout-related", items[0]?.product.categoryId], queryFn: () => listProducts({ categoryId: items[0]?.product.categoryId, status: "active", limit: 4 }), enabled: !!items[0]?.product.categoryId });
  const order = useMutation({ mutationFn: () => placeOrder(toShipping(selected!)), onSuccess: (result) => { queryClient.invalidateQueries({ queryKey: ["cart"] }); setConfirmed(result.id); push("Order placed", "success"); }, onError: (error: any) => push(error?.response?.data?.error?.message || "Could not place order", "error") });
  const saveAddress = useMutation({ mutationFn: ({ id, data }: { id?: string; data: addressesApi.AddressInput }) => id ? addressesApi.updateAddress(id, data) : addressesApi.createAddress(data), onSuccess: (address) => { queryClient.invalidateQueries({ queryKey: ["addresses"] }); setSelectedId(address.id); setEditOpen(false); push("Delivery address saved", "success"); }, onError: (error: any) => push(error?.response?.data?.error?.message || "Could not save address", "error") });
  if (confirmed) return <Success navigate={navigate} />;
  if (cartQuery.isSuccess && !items.length) return <div className="min-h-screen bg-bg"><Navbar /><PageContainer className="max-w-lg"><EmptyState title="Your cart is empty" description="Add products before checking out." action={<Button onClick={() => navigate("/discover")}>Start browsing</Button>} /></PageContainer></div>;
  if (addresses.isSuccess && addresses.data.length === 0) return <div className="min-h-screen bg-bg"><Navbar /><PageContainer className="max-w-xl py-8"><Card><h1 className="font-display text-2xl">Add a delivery address</h1><p className="text-sm text-text-muted mt-1 mb-5">Save your address to continue securely to checkout.</p><AddressForm busy={saveAddress.isPending} onSave={(data) => saveAddress.mutate({ data })} /></Card></PageContainer></div>;
  const quantityFor = (item: typeof items[number]) => {
    const draft = draftQuantities[item.id];
    if (!Number.isFinite(draft)) return item.quantity;
    return Math.min(item.product.stock, Math.max(item.product.moq, draft));
  };
  const itemCount = items.reduce((sum, item) => sum + quantityFor(item), 0);
  const subtotal = items.reduce((sum, item) => sum + Number(item.product.price) * quantityFor(item), 0);
  const fees = 0, discount = 0, total = subtotal + fees - discount;
  const similarSection = <section><div className="flex items-center justify-between mb-3"><h2 className="font-display text-xl">Similar fabrics</h2><Button variant="ghost" size="sm" onClick={() => navigate("/discover")}>Browse more <ChevronRight className="h-4 w-4" /></Button></div><ProductGrid products={(related.data?.items ?? []).filter((product) => !items.some((item) => item.productId === product.id))} isLoading={related.isLoading} isError={related.isError} onRetry={() => related.refetch()} emptyTitle="More fabrics coming soon" emptyDescription="Explore the full catalog for more options." /></section>;
  return <div className="min-h-screen bg-bg pb-36"><Navbar /><PageContainer className="max-w-[1180px] py-5 md:py-7"><h1 className="font-display text-2xl md:text-3xl mb-5">Checkout</h1>
    <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1.65fr)_360px] gap-5 lg:gap-7 items-start">
      <div className="flex flex-col gap-5">
        {selected && <DeliveryCard address={selected} onChange={() => setPickerOpen(true)} onEdit={() => setEditOpen(true)} />}
        <Card className="p-0 overflow-hidden"><div className="px-4 py-3 border-b border-border"><h2 className="font-500">Items in your order</h2></div>{items.map((item) => <CheckoutItem key={item.id} item={item} quantity={quantityFor(item)} disabled={updateItem.isPending || removeItem.isPending} onDraftChange={(quantity) => setDraftQuantities((current) => ({ ...current, [item.id]: quantity }))} onUpdate={(quantity) => updateItem.mutate({ itemId: item.id, quantity })} onRemove={() => removeItem.mutate(item.id)} />)}</Card>
        <div className="hidden lg:block">{similarSection}</div>
      </div>
      <Card className="lg:sticky lg:top-24"><h2 className="font-500 text-lg pb-3 border-b border-border">Price details</h2><div ref={orderActionRef}><div className="flex flex-col gap-3 py-4 text-sm"><Price label={`Price (${itemCount} items)`} value={subtotal} /><Price label="Delivery fees" value={fees} /><Price label="Discounts" value={-discount} success /><div className="border-t border-border pt-3"><Price label="Total amount" value={total} strong /></div></div><p className="rounded-sm bg-success/10 text-success text-sm px-3 py-2 mb-4">Your order is protected with secure supplier fulfillment.</p><Button className="w-full" disabled={!selected || order.isPending} loading={order.isPending} onClick={() => order.mutate()}>{selected ? "Place order" : "Add delivery address to continue"}</Button></div></Card>
      <div className="lg:hidden">{similarSection}</div>
    </div></PageContainer>
    {selected && <div className={`fixed inset-x-0 z-[45] border-t border-border bg-surface p-3 shadow-modal transition-all duration-200 ease-out md:hidden ${!orderActionVisible ? "translate-y-0 opacity-100" : "pointer-events-none translate-y-3 opacity-0"}`} style={{ bottom: "calc(3.5rem + env(safe-area-inset-bottom))" }}><div className="mx-auto flex max-w-lg items-center gap-3"><div className="min-w-0"><p className="text-xs text-text-muted">Total amount</p><p className="font-display text-lg">{formatCurrency(total)}</p></div><Button className="ml-auto" loading={order.isPending} onClick={() => order.mutate()}>Place order</Button></div></div>}
    <AddressPicker open={pickerOpen} addresses={addresses.data ?? []} selectedId={selectedId} onClose={() => setPickerOpen(false)} onChoose={(id) => { setSelectedId(id); setPickerOpen(false); }} />
    <Modal open={editOpen} onClose={() => setEditOpen(false)} title="Edit delivery address" size="md"><AddressForm initial={selected ?? undefined} busy={saveAddress.isPending} onSave={(data) => saveAddress.mutate({ id: selected?.id, data })} /></Modal>
  </div>;
}

function DeliveryCard({ address, onChange, onEdit }: { address: Address; onChange: () => void; onEdit: () => void }) { return <Card><div className="flex items-start gap-3"><MapPin className="h-5 w-5 text-primary mt-0.5" /><div className="min-w-0 flex-1"><p className="text-sm"><span className="font-600">Deliver to {address.fullName}</span> <span className="text-text-muted">{address.postalCode}</span> <span className="ml-2 rounded-sm bg-bg px-2 py-0.5 text-xs uppercase">{address.label}</span></p><p className="text-sm text-text-muted mt-1 line-clamp-1">{address.addressLine}, {address.city}, {address.state}</p></div><div className="flex gap-1"><Button variant="ghost" size="sm" onClick={onEdit} aria-label="Edit address"><Pencil className="h-4 w-4" /></Button><Button variant="secondary" size="sm" onClick={onChange}>Change</Button></div></div></Card>; }
function CheckoutItem({ item, quantity, onDraftChange, onUpdate, onRemove, disabled }: { item: ReturnType<typeof useCart>["items"][number]; quantity: number; onDraftChange: (quantity: number) => void; onUpdate: (quantity: number) => void; onRemove: () => void; disabled: boolean }) { const { product } = item; const [draft, setDraft] = useState(String(item.quantity)); useEffect(() => setDraft(String(item.quantity)), [item.quantity]); const commit = () => { const entered = Number(draft); const safeQuantity = Number.isInteger(entered) ? Math.min(product.stock, Math.max(product.moq, entered)) : product.moq; setDraft(String(safeQuantity)); onDraftChange(safeQuantity); if (safeQuantity !== item.quantity) onUpdate(safeQuantity); }; const change = (value: string) => { setDraft(value); const entered = Number(value); onDraftChange(Number.isFinite(entered) ? Math.min(product.stock, Math.max(product.moq, entered)) : product.moq); }; return <div className="p-4 border-b border-border last:border-0"><div className="grid grid-cols-[100px_minmax(0,1fr)] gap-4"><div className="aspect-square rounded-sm bg-bg overflow-hidden">{product.images[0] && <img src={product.images[0]} alt={product.name} className="h-full w-full object-cover" />}</div><div className="min-w-0"><h3 className="font-500 line-clamp-1">{product.name}</h3><p className="text-sm text-text-muted line-clamp-2 mt-1">{product.description}</p><p className="text-xs text-text-muted mt-2">Seller: {product.supplier?.businessName ?? "Verified supplier"}</p><p className="font-500 mt-3">{formatCurrency(Number(product.price))} <span className="text-xs text-text-muted font-normal">per {product.unit}</span></p></div></div><div className="flex items-center justify-between mt-4 text-sm"><div><input aria-label={`Quantity for ${product.name}`} className="h-9 w-20 rounded-sm border border-border px-2 text-center" type="number" min={product.moq} max={product.stock} value={draft} disabled={disabled} onChange={(e) => change(e.target.value)} onBlur={commit} onKeyDown={(e) => e.key === "Enter" && e.currentTarget.blur()} /><p className="text-xs text-text-muted mt-1">MOQ: {product.moq}</p></div><div className="flex items-center gap-2"><span className="font-600">{formatCurrency(Number(product.price) * quantity)}</span><Button variant="ghost" size="sm" className="h-9 w-9 p-0 text-error" disabled={disabled} onClick={onRemove} aria-label={`Remove ${product.name} from checkout`} title="Remove from checkout"><Trash2 className="h-4 w-4" /></Button></div></div></div>; }
function Price({ label, value, strong, success }: { label: string; value: number; strong?: boolean; success?: boolean }) { return <div className={`flex justify-between ${strong ? "font-600 text-base" : ""} ${success ? "text-success" : ""}`}><span>{label}</span><span>{value === 0 ? "Free" : `${value < 0 ? "−" : ""}${formatCurrency(Math.abs(value))}`}</span></div>; }
function toShipping(address: Address): ShippingInfo { const { fullName, countryCode, phone, addressLine, city, state, postalCode, notes } = address; return { fullName, countryCode, phone, addressLine, city, state, postalCode, notes }; }
function Success({ navigate }: { navigate: (to: string) => void }) { return <div className="min-h-screen bg-bg"><Navbar /><PageContainer className="max-w-lg"><Card><div className="text-center py-8"><CheckCircle2 className="h-12 w-12 text-success mx-auto mb-3" /><h1 className="font-display text-2xl">Order confirmed</h1><p className="text-text-muted mt-2">Your suppliers have been notified.</p><Button className="mt-5" onClick={() => navigate("/buyer/orders")}>View order status</Button></div></Card></PageContainer></div>; }
function AddressPicker({ open, addresses, selectedId, onClose, onChoose }: { open: boolean; addresses: Address[]; selectedId: string | null; onClose: () => void; onChoose: (id: string) => void }) { return <Modal open={open} onClose={onClose} title="Choose delivery address" size="md"><div className="flex flex-col gap-2">{addresses.map((address) => <button key={address.id} onClick={() => onChoose(address.id)} className={`text-left rounded-sm border p-3 transition-fast ${selectedId === address.id ? "border-primary bg-primary/5" : "border-border hover:bg-bg"}`}><p className="font-500">{address.label} · {address.fullName}</p><p className="text-sm text-text-muted mt-1">{address.addressLine}, {address.city}, {address.state} {address.postalCode}</p></button>)}</div></Modal>; }
function AddressForm({ initial, busy, onSave }: { initial?: Address; busy: boolean; onSave: (data: addressesApi.AddressInput) => void }) { const [form, setForm] = useState<addressesApi.AddressInput>(blank()); useEffect(() => { if (initial) setForm({ label: initial.label, fullName: initial.fullName, countryCode: initial.countryCode, phone: initial.phone, addressLine: initial.addressLine, city: initial.city, state: initial.state, postalCode: initial.postalCode, notes: initial.notes ?? "" }); }, [initial]); const set = <K extends keyof addressesApi.AddressInput>(key: K, value: addressesApi.AddressInput[K]) => setForm((current) => ({ ...current, [key]: value })); return <form className="flex flex-col gap-3" onSubmit={(event) => { event.preventDefault(); onSave(form); }}><Input label="Address label" required value={form.label} onChange={(event) => set("label", event.target.value)} /><Input label="Full name" required value={form.fullName} onChange={(event) => set("fullName", event.target.value)} /><div className="grid grid-cols-[88px_1fr] gap-3"><Input label="Code" required value={form.countryCode} onChange={(event) => set("countryCode", event.target.value.replace(/[^+\d]/g, ""))} /><Input label="Phone" required inputMode="numeric" value={form.phone} onChange={(event) => set("phone", event.target.value.replace(/\D/g, ""))} /></div><Textarea label="Address" required value={form.addressLine} onChange={(event) => set("addressLine", event.target.value)} /><div className="grid grid-cols-2 gap-3"><Input label="City" required value={form.city} onChange={(event) => set("city", event.target.value)} /><Input label="State" required value={form.state} onChange={(event) => set("state", event.target.value)} /></div><Input label="Postal code" required value={form.postalCode} onChange={(event) => set("postalCode", event.target.value)} /><Button type="submit" loading={busy}>Save delivery address</Button></form>; }
